\contentsline {lstlisting}{\numberline {1}{\ignorespaces \textnormal {\textsc {GRust}}\xspace program for the Adaptive Cruise Control example.}}{45}{lstlisting.3.1}%
\contentsline {lstlisting}{\numberline {2}{\ignorespaces \textnormal {\textsc {GReusot}}\xspace specification of a function.}}{49}{lstlisting.3.2}%
\contentsline {lstlisting}{\numberline {3}{\ignorespaces \textnormal {\textsc {GReusot}}\xspace specification of a component.}}{50}{lstlisting.3.3}%
\contentsline {lstlisting}{\numberline {4}{\ignorespaces Usage of the \texttt {grust!} macro.}}{91}{lstlisting.3.4}%
\contentsline {lstlisting}{\numberline {5}{\ignorespaces Generated \textnormal {\textsc {Rust}}\xspace code for a \textnormal {\textsc {GRust}}\xspace function.}}{105}{lstlisting.3.5}%
\contentsline {lstlisting}{\numberline {6}{\ignorespaces Generated \textnormal {\textsc {Rust}}\xspace code for a \textnormal {\textsc {GRust}}\xspace component.}}{106}{lstlisting.3.6}%
\contentsline {lstlisting}{\numberline {7}{\ignorespaces Generated code for the Adaptive Cruise Control component.}}{106}{lstlisting.3.7}%
\contentsline {lstlisting}{\numberline {8}{\ignorespaces Dispatch mechanism of the main asynchronous loop.}}{109}{lstlisting.3.8}%
\contentsline {lstlisting}{\numberline {9}{\ignorespaces \textnormal {\textsc {Rust}}\xspace data structures generated by a \textnormal {\textsc {GRust}}\xspace service.}}{117}{lstlisting.3.9}%
\contentsline {lstlisting}{\numberline {10}{\ignorespaces \textnormal {\textsc {Rust}}\xspace input handler for a \textnormal {\textsc {GRust}}\xspace service.}}{118}{lstlisting.3.10}%
\contentsline {lstlisting}{\numberline {11}{\ignorespaces Runtime architecture for a \textnormal {\textsc {GRust}}\xspace service.}}{119}{lstlisting.3.11}%
\contentsline {lstlisting}{\numberline {12}{\ignorespaces Asynchronous run loop of the runtime for a \textnormal {\textsc {GRust}}\xspace service.}}{119}{lstlisting.3.12}%
\contentsline {lstlisting}{\numberline {13}{\ignorespaces Main \texttt {run} function that launches a service.}}{120}{lstlisting.3.13}%
\contentsline {lstlisting}{\numberline {14}{\ignorespaces \textnormal {\textsc {GReusot}}\xspace specification of a function.}}{123}{lstlisting.3.14}%
\contentsline {lstlisting}{\numberline {15}{\ignorespaces Generated code for the \textnormal {\textsc {GReusot}}\xspace specification of a function.}}{124}{lstlisting.3.15}%
\contentsline {lstlisting}{\numberline {16}{\ignorespaces \textnormal {\textsc {GReusot}}\xspace specification of a component.}}{124}{lstlisting.3.16}%
\contentsline {lstlisting}{\numberline {17}{\ignorespaces Generated code for the \textnormal {\textsc {GReusot}}\xspace specification of a component.}}{125}{lstlisting.3.17}%
\contentsline {lstlisting}{\numberline {18}{\ignorespaces Extract of an implementation of a Kalman Filter encoded in \textnormal {\textsc {GRust}}\xspace .}}{136}{lstlisting.3.18}%
\contentsline {lstlisting}{\numberline {19}{\ignorespaces Derived implementation of the Over-Speed Alert in \textnormal {\textsc {GRust}}\xspace .}}{138}{lstlisting.3.19}%
